// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protocol/student.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_protocol_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_protocol_student_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type SearchByID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByID) Reset() {
	*x = SearchByID{}
	mi := &file_protocol_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByID) ProtoMessage() {}

func (x *SearchByID) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByID.ProtoReflect.Descriptor instead.
func (*SearchByID) Descriptor() ([]byte, []int) {
	return file_protocol_student_proto_rawDescGZIP(), []int{1}
}

func (x *SearchByID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SearchByName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByName) Reset() {
	*x = SearchByName{}
	mi := &file_protocol_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByName) ProtoMessage() {}

func (x *SearchByName) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByName.ProtoReflect.Descriptor instead.
func (*SearchByName) Descriptor() ([]byte, []int) {
	return file_protocol_student_proto_rawDescGZIP(), []int{2}
}

func (x *SearchByName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protocol_student_proto protoreflect.FileDescriptor

const file_protocol_student_proto_rawDesc = "" +
	"\n" +
	"\x16protocol/student.proto\"?\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"\x1c\n" +
	"\n" +
	"SearchByID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\"\n" +
	"\fSearchByName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2m\n" +
	"\x0eStudentService\x12)\n" +
	"\x0eGetStudentByID\x12\v.SearchByID\x1a\b.Student\"\x00\x120\n" +
	"\x11GetStudentsByName\x12\r.SearchByName\x1a\b.Student\"\x000\x01B\vZ\t/protocolb\x06proto3"

var (
	file_protocol_student_proto_rawDescOnce sync.Once
	file_protocol_student_proto_rawDescData []byte
)

func file_protocol_student_proto_rawDescGZIP() []byte {
	file_protocol_student_proto_rawDescOnce.Do(func() {
		file_protocol_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_student_proto_rawDesc), len(file_protocol_student_proto_rawDesc)))
	})
	return file_protocol_student_proto_rawDescData
}

var file_protocol_student_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_student_proto_goTypes = []any{
	(*Student)(nil),      // 0: Student
	(*SearchByID)(nil),   // 1: SearchByID
	(*SearchByName)(nil), // 2: SearchByName
}
var file_protocol_student_proto_depIdxs = []int32{
	1, // 0: StudentService.GetStudentByID:input_type -> SearchByID
	2, // 1: StudentService.GetStudentsByName:input_type -> SearchByName
	0, // 2: StudentService.GetStudentByID:output_type -> Student
	0, // 3: StudentService.GetStudentsByName:output_type -> Student
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_student_proto_init() }
func file_protocol_student_proto_init() {
	if File_protocol_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_student_proto_rawDesc), len(file_protocol_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_student_proto_goTypes,
		DependencyIndexes: file_protocol_student_proto_depIdxs,
		MessageInfos:      file_protocol_student_proto_msgTypes,
	}.Build()
	File_protocol_student_proto = out.File
	file_protocol_student_proto_goTypes = nil
	file_protocol_student_proto_depIdxs = nil
}
